version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-todo
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5414:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: